allow_equivalents: asserted-only
catalog_file: catalog-v001.xml
components: null
contact: null
contributors: null
creators: null
description: None
dosdp_tools_options: --obo-prefixes=true
edit_format: owl
exclude_tautologies: structural
export_formats:
- owl
- obo
- json
git_user: ''
github_org: EBISPOT
gzip_main: false
id: covoc
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: efo
    mirror_from: http://www.ebi.ac.uk/efo/efo.owl
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: https://creativecommons.org/licenses/unspecified
namespaces: null
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: full
public_release: none
public_release_assets: null
reasoner: ELK
release_artefacts:
- full
- base
release_date: false
repo: covoc
report_fail_on: none
robot_java_args: -Xmx8G
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: Coronavirus Vocabulary
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: true
use_external_date: false
